runtime: python37
entrypoint: gunicorn -b :$PORT lmnop_project.wsgi

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto

env_variables:
  MUSIC_FAN_PW: concertsarelame2021

beta_settings:
  cloud_sql_instance: lmnop-311407:us-central1:lmnop-db